### ISSUE TITLE
got a segfault on osx

### ISSUE THREAD

**Issue by spuky** [bitPico/bcash_network_test_tool_01#4]
was running on https://github.com/bitPico/bcash_network_test_tool_01/commit/48762141c5b302abea8a2ca8020cd879b885b085

here is the output of the debug log at that time... don't know if that helps feel free to close if usless info...

[INFO] - handle_message: Got tx 0ca94138c7679f354efbab5561f7125fbb8879986419a548a4742949699087f8
[INFO] - handle_message: Got tx 8f546247296654e0377e87b6a85c350915f2dd9099df79fcf4da6ea82e9cfadf
[INFO] - handle_message: Got tx 1e70a0b7a5e2108622d2c000e961cab39b1e2340332c9780e8e182d776efe3ac
[INFO] - handle_message: Got tx 34b61b9cc4647e1b593ccd3beb14953176f089b2e0c42338767878ac1102c723
[ERROR] - operator(): TCP connection (ping) timed out, calling stop.
[INFO] - handle_message: Got tx c773859ed2e20456b50a6bf596bf845be98d04200da5025e2756a37a89bcbbe9
[ERROR] - operator(): TCP transport on_read callback failed, what = std::bad_alloc.

**Comment by bitPico** [comment]
need more details
