### ISSUE TITLE
if blocked by the BCH rack connecting to the "decentralised" network  is almost impossible

### ISSUE THREAD

**Issue by spuky** [bitPico/bcash_network_test_tool_01#5]
2 hours in and still getting:

[INFO] - handle_message: Got tx 58d14b752b7acca3731702d265f70498c332355af66b645aa41f6509a4a2c720
[INFO] - handle_message: Got tx 58d14b752b7acca3731702d265f70498c332355af66b645aa41f6509a4a2c720
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 1332499780.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 795512211.
[INFO] - handle_message: TCP connection 553577851 no bloom support in services, calling stop.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 2661136458.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 1038321125.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 2210522473.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 2737537832.
[INFO] - on_peer_headers_first: Stack, waiting for more headers before starting block fetching.
[INFO] - on_peer_headers_first: Stack, detected headers stalled, disconnecting peer 3277079772.

about 10 connections... seem to be closing them before getting enough headers...

**Comment by spuky** [comment]
seems the decided to not block my IP anymore... up and running again....

**Comment by bitPico** [comment]
closing as no issue

*Note: Add some known long running decentralized nodes to the bootstrap list.
